#########################
#MAKEFILE pour le projet#
#########################

COMPILER=gcc
OPTIONS= -W -WALL -std=c99 -o
#changer le nom de l'exécutable pour la spec du TP2
EXEC=TP2
all:mod_regex
mod_regex:	mod_regex.h
	echo "compilation du module d'expression regulieres"
	${COMPILER} ${OPTIONS} mod_regex.o

clean:
	rm -rf *.o
